"""The image catalog: every usable product image in the three MOTU repositories.

Each entry is (repository, file name, product, kind[, note]). The repositories
hold 246 image files; byte-identical duplicates collapse to 214, and the handful
that are not MOTU product imagery (a Moog modular, a Korg synth, generic stock
icons) are left out here, each with its reason, so the omission is on record.

  product   16a | 848 | 10pre | switch | ul | 828 | m2 | m4 | m6 | avb | ul828 | m
            (the last three mean "the series", for shared material)
  kind      render   transparent studio render of the unit
            hero     studio photograph of the unit on a sweep
            life     the unit in a real room
            panel    front / rear elevation
            detail   close-up of a panel region
            cm5      CueMix 5 screenshot (UltraLite-mk5 / 828 DSP mixer)
            cmpro    CueMix Pro screenshot (AVB Series DSP mixer)
            diagram  connection / latency / network diagram
            badge    ESS, Thunderbolt, USB, Milan marks
            bundle   the software bundle artwork
            logo     the CueMix app logos
"""

AVB = "high-end-video-motu-avb-series-16a-848-10pre-avb-switch-shivansh-electronics-kolkata"
MS = "motu-m-series-m2-m4-m6-high-end-video-shivansh-electronics-kolkata"
UL = "motu-ultralitemk5-828"

C = [
    # ── MOTU 10pre ────────────────────────────────────────────────────────
    (AVB, "MOTU 10PRE NEWLY ADDED (1).png", "10pre", "render"),
    (AVB, "MOTU 10PRE NEWLY ADDED (2).png", "10pre", "render"),
    (AVB, "MOTU 10PRE NEWLY ADDED (3).png", "10pre", "render"),
    (AVB, "MOTU 10PRE NEWLY ADDED.png", "10pre", "render"),
    (AVB, "MOTU 10PRE NEWLY ADDED.jpg", "10pre", "hero"),
    (AVB, "MOTU 10pre (1).jpg", "10pre", "hero", "rear, cabled"),
    (AVB, "MOTU 10pre (1).png", "avb", "cmpro", "routing grid"),
    (AVB, "MOTU 10pre (10).jpg", "avb", "cmpro", "patchbay"),
    (AVB, "MOTU 10pre (10).png", "10pre", "diagram"),
    (AVB, "MOTU 10pre (11).jpg", "10pre", "detail", "inserts + combo"),
    (AVB, "MOTU 10pre (11).png", "10pre", "diagram"),
    (AVB, "MOTU 10pre (12).jpg", "10pre", "detail", "display"),
    (AVB, "MOTU 10pre (12).png", "10pre", "diagram", "round trip"),
    (AVB, "MOTU 10pre (13).jpg", "10pre", "detail", "4 combo inputs"),
    (AVB, "MOTU 10pre (14).jpg", "avb", "cmpro", "mixer on display"),
    (AVB, "MOTU 10pre (14).png", "avb", "cmpro", "iPad wireless control"),
    (AVB, "MOTU 10pre (15).jpg", "avb", "cmpro", "monitor group"),
    (AVB, "MOTU 10pre (16).jpg", "avb", "life", "control room"),
    (AVB, "MOTU 10pre (17).jpg", "10pre", "detail", "display"),
    (AVB, "MOTU 10pre (18).jpg", "10pre", "detail", "line outs"),
    (AVB, "MOTU 10pre (2).jpg", "10pre", "detail", "network / optical / line"),
    (AVB, "MOTU 10pre (20).jpg", "10pre", "detail", "talkback buttons"),
    (AVB, "MOTU 10pre (21).jpg", "avb", "cmpro", "patchbay"),
    (AVB, "MOTU 10pre (22).jpg", "10pre", "detail", "network / optical"),
    # "MOTU 10pre (23).jpg" is a Moog modular, not MOTU hardware: left out.
    (AVB, "MOTU 10pre (24).jpg", "avb", "cmpro", "iPad"),
    (AVB, "MOTU 10pre (25).jpg", "avb", "diagram", "network"),
    (AVB, "MOTU 10pre (26).jpg", "avb", "badge", "ESS"),
    (AVB, "MOTU 10pre (27).jpg", "avb", "cmpro", "reverb"),
    (AVB, "MOTU 10pre (28).jpg", "avb", "badge", "Thunderbolt"),
    (AVB, "MOTU 10pre (29).jpg", "10pre", "detail", "headphones"),
    (AVB, "MOTU 10pre (3).jpg", "avb", "cmpro", "gate + compressor"),
    (AVB, "MOTU 10pre (4).jpg", "avb", "cmpro", "EQ"),
    (AVB, "MOTU 10pre (4).png", "10pre", "panel", "front"),
    (AVB, "MOTU 10pre (5).jpg", "avb", "cmpro", "device discovery"),
    (AVB, "MOTU 10pre (6).jpg", "avb", "cmpro", "device"),
    (AVB, "MOTU 10pre (7).jpg", "avb", "cmpro", "inputs"),
    (AVB, "MOTU 10pre (8).jpg", "avb", "cmpro", "mixer"),
    (AVB, "MOTU 10pre (8).png", "10pre", "panel", "rear"),
    (AVB, "MOTU 10pre (9).jpg", "avb", "cmpro", "outputs"),
    # ── MOTU 16A ──────────────────────────────────────────────────────────
    (AVB, "MOTU 16A (1).jpg", "16a", "life", "desk"),
    (AVB, "MOTU 16A (1).png", "avb", "logo", "CueMix Pro"),
    (AVB, "MOTU 16A (10).jpg", "avb", "cmpro", "inputs"),
    (AVB, "MOTU 16A (10).png", "16a", "panel", "front, full width"),
    (AVB, "MOTU 16A (11).jpg", "avb", "cmpro", "mixer"),
    (AVB, "MOTU 16A (11).png", "16a", "panel", "rear, full width"),
    (AVB, "MOTU 16A (12).jpg", "avb", "cmpro", "mixer on display"),
    (AVB, "MOTU 16A (12).png", "16a", "panel", "full width"),
    (AVB, "MOTU 16A (13).jpg", "avb", "cmpro", "mixer"),
    (AVB, "MOTU 16A (13).png", "16a", "panel", "rear"),
    (AVB, "MOTU 16A (14).jpg", "avb", "cmpro", "sections"),
    (AVB, "MOTU 16A (15).jpg", "avb", "cmpro", "EQ"),
    (AVB, "MOTU 16A (16).jpg", "avb", "cmpro", "patchbay"),
    (AVB, "MOTU 16A (17).jpg", "avb", "cmpro", "patchbay"),
    (AVB, "MOTU 16A (18).jpg", "16a", "life", "laptop on the 16A"),
    (AVB, "MOTU 16A (19).jpg", "avb", "bundle"),
    (AVB, "MOTU 16A (2).jpg", "16a", "detail", "displays"),
    (AVB, "MOTU 16A (2).png", "avb", "bundle", "DAW"),
    (AVB, "MOTU 16A (21).jpg", "16a", "detail", "rear jacks"),
    (AVB, "MOTU 16A (24).jpg", "16a", "detail", "line outs"),
    (AVB, "MOTU 16A (25).jpg", "16a", "hero", "rear, cabled"),
    (AVB, "MOTU 16A (26).jpg", "avb", "cmpro", "routing grid"),
    (AVB, "MOTU 16A (28).jpg", "16a", "detail", "network / optical"),
    (AVB, "MOTU 16A (3).png", "avb", "bundle", "DAW"),
    (AVB, "MOTU 16A (4).png", "16a", "panel", "front"),
    (AVB, "MOTU 16A (5).jpg", "avb", "diagram", "network"),
    (AVB, "MOTU 16A (5).png", "16a", "diagram"),
    (AVB, "MOTU 16A (6).jpg", "avb", "cmpro", "device discovery"),
    (AVB, "MOTU 16A (6).png", "16a", "diagram", "round trip"),
    (AVB, "MOTU 16A (7).jpg", "avb", "cmpro", "dynamics"),
    (AVB, "MOTU 16A (7).png", "avb", "cmpro", "iPad wireless control"),
    (AVB, "MOTU 16A (8).png", "16a", "panel", "rear"),
    (AVB, "MOTU 16A (9).jpg", "avb", "cmpro", "outputs"),
    (AVB, "MOTU 16A (9).png", "16a", "panel", "front"),
    (AVB, "MOTU 16A NEWLY ADDED (1).png", "16a", "render"),
    (AVB, "MOTU 16A NEWLY ADDED (2).png", "16a", "render"),
    (AVB, "MOTU 16A NEWLY ADDED (3).png", "16a", "render"),
    (AVB, "MOTU 16A NEWLY ADDED (4).png", "16a", "render"),
    (AVB, "MOTU 16A NEWLY ADDED.jpg", "16a", "hero"),
    # "MOTU 16A (23).jpg" (a USB cable) and "MOTU 10pre (13).png" (the same
    # cable) are accessories, not the product: left out.
    # ── MOTU 848 ──────────────────────────────────────────────────────────
    (AVB, "MOTU 848 (1).jpg", "avb", "life", "control room"),
    (AVB, "MOTU 848 (10).jpg", "avb", "bundle"),
    (AVB, "MOTU 848 (11).jpg", "avb", "bundle"),
    (AVB, "MOTU 848 (11).png", "848", "panel", "front"),
    (AVB, "MOTU 848 (12).png", "848", "panel", "rear"),
    (AVB, "MOTU 848 (15).jpg", "848", "detail", "headphones"),
    (AVB, "MOTU 848 (16).jpg", "848", "detail", "line outs"),
    (AVB, "MOTU 848 (17).jpg", "848", "hero", "rear, cabled"),
    (AVB, "MOTU 848 (18).jpg", "848", "detail", "network / optical / line"),
    (AVB, "MOTU 848 (2).png", "avb", "bundle", "instruments"),
    (AVB, "MOTU 848 (20).jpg", "848", "detail", "inserts + combo"),
    (AVB, "MOTU 848 (22).jpg", "848", "detail", "display"),
    (AVB, "MOTU 848 (23).jpg", "848", "detail", "4 combo inputs"),
    (AVB, "MOTU 848 (24).jpg", "avb", "cmpro", "mixer on display"),
    (AVB, "MOTU 848 (25).jpg", "avb", "cmpro", "monitor group"),
    (AVB, "MOTU 848 (26).jpg", "avb", "cmpro", "patchbay"),
    (AVB, "MOTU 848 (3).jpg", "avb", "cmpro", "routing grid"),
    (AVB, "MOTU 848 (3).png", "avb", "badge", "Milan"),
    (AVB, "MOTU 848 (4).jpg", "848", "detail", "display"),
    (AVB, "MOTU 848 (5).jpg", "avb", "bundle"),
    (AVB, "MOTU 848 (6).png", "848", "panel", "front"),
    (AVB, "MOTU 848 (7).png", "848", "diagram"),
    (AVB, "MOTU 848 (8).png", "848", "diagram", "round trip"),
    (AVB, "MOTU 848 (9).png", "avb", "cmpro", "iPad wireless control"),
    (AVB, "MOTU 848 NEWLY ADDED (1).jpg", "848", "hero"),
    (AVB, "MOTU 848 NEWLY ADDED (1).png", "848", "render"),
    (AVB, "MOTU 848 NEWLY ADDED (2).png", "848", "render"),
    (AVB, "MOTU 848 NEWLY ADDED (3).png", "848", "render"),
    (AVB, "MOTU 848 NEWLY ADDED (4).png", "848", "render"),
    # "MOTU 848 (13).jpg" repeats the Thunderbolt mark: left out.
    # ── MOTU AVB Switch ───────────────────────────────────────────────────
    (AVB, "MOTU AVB SWITCH (1).jpg", "switch", "hero"),
    (AVB, "MOTU AVB SWITCH (1).png", "switch", "diagram", "AVB network"),
    (AVB, "MOTU AVB SWITCH (2).jpg", "switch", "hero"),
    (AVB, "MOTU AVB SWITCH (3).jpg", "switch", "hero", "top"),
    # (2).png is a 120 px IEEE mark; (3).png a stock cable; (4).jpg, (4).png and
    # (5).png are stock clock / ribbon / gauge icons: left out.
    # ── MOTU M2 / M4 / M6 ─────────────────────────────────────────────────
    (MS, "MOTU M2 (1).jpg", "m2", "life"),
    (MS, "MOTU M2 (10).jpg", "m2", "life", "conference table"),
    (MS, "MOTU M2 (2).png", "m2", "panel", "front"),
    (MS, "MOTU M2 (3).jpg", "m2", "life"),
    (MS, "MOTU M2 (4).jpg", "m2", "life"),
    (MS, "MOTU M2 (5).jpg", "m2", "life"),
    (MS, "MOTU M2 (6).jpg", "m2", "life", "overhead"),
    (MS, "MOTU M2 (8).jpg", "m2", "hero"),
    (MS, "MOTU M2 (9).png", "m2", "panel", "rear"),
    (MS, "MOTU M4 (1).jpg", "m4", "life"),
    (MS, "MOTU M4 (1).png", "m4", "panel", "front"),
    (MS, "MOTU M4 (2).jpg", "m4", "life"),
    (MS, "MOTU M4 (2).png", "m4", "panel", "rear"),
    (MS, "MOTU M4 (4).jpg", "m4", "hero"),
    (MS, "MOTU M4 (5).jpg", "m4", "life", "drummer overhead"),
    (MS, "MOTU M4 (6).jpg", "m4", "life", "keys"),
    (MS, "MOTU M4 (7).jpg", "m4", "life", "desk"),
    (MS, "MOTU M4 (8).jpg", "m", "bundle"),
    (MS, "MOTU M6 (1).jpg", "m6", "detail", "meter"),
    (MS, "MOTU M6 (1).png", "m6", "panel", "front"),
    (MS, "MOTU M6 (10).jpg", "m6", "life", "desk"),
    (MS, "MOTU M6 (2).jpg", "m6", "life", "synth desk"),
    (MS, "MOTU M6 (2).png", "m6", "panel", "rear"),
    (MS, "MOTU M6 (3).jpg", "m6", "life", "keys"),
    (MS, "MOTU M6 (4).jpg", "m6", "life", "drums"),
    (MS, "MOTU M6 (5).jpg", "m6", "life", "podcast"),
    (MS, "MOTU M6 (6).jpg", "m6", "life", "studio desk"),
    (MS, "MOTU M6 (7).jpg", "m6", "life", "live duo"),
    (MS, "MOTU M6 (8).jpg", "m6", "life", "studio"),
    (MS, "MOTU M6 (9).jpg", "m6", "life", "couch"),
    # ── MOTU 828 ──────────────────────────────────────────────────────────
    (UL, "MOTU 828 (1).jpg", "828", "detail", "line outs"),
    (UL, "MOTU 828 (1).png", "828", "render"),
    (UL, "MOTU 828 (10).jpg", "828", "detail", "optical / S/PDIF / MIDI"),
    (UL, "MOTU 828 (11).png", "ul828", "bundle", "DAW"),
    (UL, "MOTU 828 (12).jpg", "ul828", "cm5", "gate + compressor"),
    (UL, "MOTU 828 (12).png", "ul828", "bundle", "DAW"),
    (UL, "MOTU 828 (13).jpg", "ul828", "cm5", "EQ"),
    (UL, "MOTU 828 (13).png", "828", "hero", "rear, cabled"),
    (UL, "MOTU 828 (14).jpg", "ul828", "cm5", "mixer"),
    (UL, "MOTU 828 (14).png", "828", "diagram", "round trip"),
    (UL, "MOTU 828 (15).jpg", "ul828", "cm5", "home"),
    (UL, "MOTU 828 (15).png", "ul828", "cm5", "iPad"),
    (UL, "MOTU 828 (16).jpg", "ul828", "cm5", "reverb"),
    (UL, "MOTU 828 (17).jpg", "ul828", "cm5", "mixer"),
    (UL, "MOTU 828 (18).jpg", "828", "life", "guitar rig"),
    (UL, "MOTU 828 (2).jpg", "ul828", "cm5", "loopback"),
    (UL, "MOTU 828 (2).png", "828", "render"),
    (UL, "MOTU 828 (20).jpg", "828", "detail", "footswitch"),
    (UL, "MOTU 828 (21).jpg", "828", "life", "desk"),
    (UL, "MOTU 828 (22).jpg", "828", "detail", "mic insert"),
    (UL, "MOTU 828 (25).jpg", "828", "life", "vocal booth"),
    (UL, "MOTU 828 (27).jpg", "ul828", "cm5", "monitor group"),
    (UL, "MOTU 828 (28).jpg", "828", "life", "laptop on the 828"),
    (UL, "MOTU 828 (3).jpg", "828", "detail", "display"),
    (UL, "MOTU 828 (3).png", "828", "panel", "front"),
    (UL, "MOTU 828 (30).jpg", "ul828", "life", "control room"),
    (UL, "MOTU 828 (31).jpg", "ul828", "badge", "USB 5 Gbps"),
    (UL, "MOTU 828 (4).jpg", "828", "detail", "optical"),
    (UL, "MOTU 828 (4).png", "828", "panel", "front"),
    (UL, "MOTU 828 (5).jpg", "828", "detail", "S/PDIF"),
    (UL, "MOTU 828 (5).png", "828", "render"),
    (UL, "MOTU 828 (6).jpg", "828", "hero"),
    (UL, "MOTU 828 (6).png", "828", "render"),
    (UL, "MOTU 828 (7).jpg", "828", "detail", "display"),
    (UL, "MOTU 828 (7).png", "828", "panel", "rear"),
    (UL, "MOTU 828 (8).png", "828", "panel", "rear"),
    (UL, "MOTU 828 (9).jpg", "828", "detail", "talkback buttons"),
    (UL, "MOTU 828 (9).png", "ul828", "logo", "CueMix 5"),
    # "MOTU 828 (11).jpg" is a Moog modular and "MOTU 828 (26).jpg" a Korg
    # synth — neither is MOTU hardware: left out.
    # ── MOTU UltraLite-mk5 ────────────────────────────────────────────────
    (UL, "MOTU UltraLite-mk5 (1).jpg", "ul", "life", "headphones"),
    (UL, "MOTU UltraLite-mk5 (1).png", "ul828", "cm5", "home"),
    (UL, "MOTU UltraLite-mk5 (10).jpg", "ul", "diagram", "round trip"),
    (UL, "MOTU UltraLite-mk5 (11).jpg", "ul", "hero", "dark"),
    (UL, "MOTU UltraLite-mk5 (12).jpg", "ul", "hero", "white"),
    (UL, "MOTU UltraLite-mk5 (13).jpg", "ul828", "cm5", "iPad"),
    (UL, "MOTU UltraLite-mk5 (14).jpg", "ul", "diagram", "connections"),
    (UL, "MOTU UltraLite-mk5 (2).jpg", "ul", "life", "headphones"),
    (UL, "MOTU UltraLite-mk5 (2).png", "ul", "detail", "display"),
    (UL, "MOTU UltraLite-mk5 (3).jpg", "ul", "life", "guitar amp"),
    (UL, "MOTU UltraLite-mk5 (3).png", "ul", "render"),
    (UL, "MOTU UltraLite-mk5 (4).jpg", "ul", "life", "iPad"),
    (UL, "MOTU UltraLite-mk5 (4).png", "ul", "diagram", "rack ears"),
    (UL, "MOTU UltraLite-mk5 (5).jpg", "ul", "life", "desk"),
    (UL, "MOTU UltraLite-mk5 (5).png", "ul", "diagram", "rack ears"),
    (UL, "MOTU UltraLite-mk5 (6).jpg", "ul828", "cm5", "gate + compressor"),
    (UL, "MOTU UltraLite-mk5 (6).png", "ul", "render"),
    (UL, "MOTU UltraLite-mk5 (7).jpg", "ul828", "cm5", "EQ"),
    (UL, "MOTU UltraLite-mk5 (7).png", "ul", "render"),
    (UL, "MOTU UltraLite-mk5 (8).jpg", "ul828", "cm5", "mixer"),
    (UL, "MOTU UltraLite-mk5 (8).png", "ul", "panel", "front"),
    (UL, "MOTU UltraLite-mk5 (9).jpg", "ul828", "cm5", "reverb"),
    (UL, "MOTU UltraLite-mk5 (9).png", "ul", "panel", "rear"),
]

SERIES = {
    "16a": "avb", "848": "avb", "10pre": "avb", "switch": "avb", "avb": "avb",
    "ul": "ul828", "828": "ul828", "ul828": "ul828",
    "m2": "m", "m4": "m", "m6": "m", "m": "m",
}
